sudo: required
dist: trusty

language: java

before_install:
      - openssl aes-256-cbc -K $encrypted_2760b77333f5_key -iv $encrypted_2760b77333f5_iv -in secrets.tar.enc -out secrets.tar -d
      - tar xvf secrets.tar
      - sudo apt-get -qq update
      - sudo apt-get -qq -y install r-base
      - sudo R CMD javareconf

